### PR TITLE
226 clean up tags and fix integration tests.

### LINKED ISSUE #226: Clean up tags and fix integration tests.
After migrating the repository to the PostgreSQL database struct tags were not adjusted. 
Some integration tests need examination and fixing.

### PR DESCRIPTION
**Pull request by bartossh**
After migrating the repository to the PostgreSQL database struct tags are adjusted in this PR.
Integration tests and stress tests are updated.

Tested.

### CODE REVIEW

File: stress/stress.go [hunk 1]
```diff
@@ -1,5 +1,164 @@
...
+
+	"github.com/pterm/pterm"
+
+	"github.com/bartossh/Computantis/fileoperations"
+	"github.com/bartossh/Computantis/wallet"
+	"github.com/bartossh/Computantis/walletmiddleware"
+)
+
+func main() {
+	serverAddress := "http://192.168.0.206"
```
Comment (dmatusiewicz-consult-red) [inline stress/stress.go]: Should we hardcode the server address? In a docker-compose we are not making any guarantees in terms of network address. Perhaps os.Env or a pre-defined  hostname ?

File: stress/stress_test.go [hunk 2]
```diff
@@ -7,80 +7,83 @@
...
 )
 
-// Run two central nodes for this test, one on port 8080 and second on 8088.
-// Create corresponding tokens to be valid in database.
+// Run adjusting serverAddress and port of each testCase.
+// This allows to have multiple nodes on the same address but different port.
+// Now address is some network address that indicates a IPv4 format.
 func TestFullClientApiCycle(t *testing.T) {
-	transactionsCount := 10000
+	serverAddress := "http://192.168.0.206"
```
Comment (dmatusiewicz-consult-red) [inline stress/stress_test.go]: Should we hardcode the server address? In a docker-compose we are not making any guarantees in terms of network address. Perhaps os.Env or a pre-defined hostname ?

File: stress/stress_test.go [hunk 3]
```diff
@@ -93,7 +96,7 @@ func TestFullClientApiCycle(t *testing.T) {
 	for _, c := range testCases {
 		wg.Add(1)
 		go func(c testCase) {
-			addr := fmt.Sprintf("http://localhost:%s", c.port)
+			addr := fmt.Sprintf("%s:%s", serverAddress, c.port)
```
Comment (dmatusiewicz-consult-red) [inline stress/stress_test.go:99]: instead of "Sprintf" - we could build and validate the URI by net/url package to parse a valid url - so we will be able to validate serverAddress. 

That is minor of course ;)

**Review by dmatusiewicz-consult-red — COMMENTED** [review]
I have added some  minor comments related to serverAddress for consideration.

File: stress/stress_test.go (hunk 2 above)
Comment (bartossh) [reply stress/stress_test.go]: Good catch. I am not sure what to place there... It is the address from the last tests. 
What do you think about leaving it as it is and creating an issue to upgrade the stress test to simple CLI using some config file?

File: stress/stress_test.go (hunk 3 above)
Comment (bartossh) [reply stress/stress_test.go:99]: It is just a stress test that will be run in a development environment, so I was treating it lightly. But sure, fair point. Will do. Thx.

File: stress/stress.go (hunk 1 above)
Comment (bartossh) [reply stress/stress.go]: This is my Raspberry PI zero address. I will try to make it more clear. 
Thanks for pointing this out.

**Review by dmatusiewicz-consult-red — APPROVED** [review]
